-- Schema for the Marlowe & Finch operations dashboard.
-- Plain SQL that runs unchanged on PostgreSQL 16 and on H2 in PostgreSQL mode (the demo profile).

CREATE TABLE carriers (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(80) NOT NULL UNIQUE,
  code  VARCHAR(8)  NOT NULL UNIQUE
);

CREATE TABLE orders (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ref     VARCHAR(16)   NOT NULL UNIQUE,
  customer_name VARCHAR(120)  NOT NULL,
  region        VARCHAR(40)   NOT NULL,
  ordered_at    DATE          NOT NULL,
  amount        NUMERIC(10,2) NOT NULL,
  status        VARCHAR(16)   NOT NULL,
  CONSTRAINT chk_orders_status CHECK (status IN ('processing', 'shipped', 'cancelled'))
);
CREATE INDEX idx_orders_ordered_at ON orders (ordered_at);
CREATE INDEX idx_orders_status ON orders (status);

-- One delivery per shipped order. delivered_date is NULL while the parcel is in transit.
-- days_late is 0 when it arrived on or before promised_date, otherwise the number of days after it.
CREATE TABLE deliveries (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       INTEGER NOT NULL UNIQUE REFERENCES orders (id),
  carrier_id     INTEGER NOT NULL REFERENCES carriers (id),
  shipped_date   DATE    NOT NULL,
  promised_date  DATE    NOT NULL,
  delivered_date DATE,
  days_late      INTEGER
);
CREATE INDEX idx_deliveries_carrier ON deliveries (carrier_id);
CREATE INDEX idx_deliveries_delivered_date ON deliveries (delivered_date);

CREATE TABLE tickets (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id  INTEGER     NOT NULL REFERENCES orders (id),
  category  VARCHAR(40) NOT NULL,
  priority  VARCHAR(8)  NOT NULL,
  status    VARCHAR(8)  NOT NULL,
  opened_at DATE        NOT NULL,
  closed_at DATE,
  CONSTRAINT chk_tickets_status CHECK (status IN ('open', 'closed'))
);
CREATE INDEX idx_tickets_opened_at ON tickets (opened_at);
CREATE INDEX idx_tickets_category ON tickets (category);
CREATE INDEX idx_tickets_status ON tickets (status);

CREATE TABLE vendors (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(80)   NOT NULL UNIQUE,
  category     VARCHAR(40)   NOT NULL,
  annual_spend NUMERIC(12,2) NOT NULL,
  contract_end DATE          NOT NULL,
  notice_days  INTEGER       NOT NULL,
  owner        VARCHAR(80)   NOT NULL
);
CREATE INDEX idx_vendors_contract_end ON vendors (contract_end);
